services:
  app:
    image: cornellappdev/chimes-dev:${IMAGE_TAG}
    env_file: .env
    volumes:
      - ./service-account-key.json:/service-account-key.json
    ports:
      - "8080:8080"
    restart: unless-stopped
